apiVersion: v1
kind: Service
metadata:
  labels:
    app: adder
  name: adder
  namespace: b6003234

spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32588
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: adder
  sessionAffinity: None
  type: LoadBalancer
