apiVersion: v1
kind: Service
metadata:
  labels:
    app: adder
  name: adder
  namespace: b6003234
  resourceVersion: "5114"
  selfLink: /api/v1/namespaces/b6003234/services/adder
  uid: d05ba3cb-55e7-445f-91a7-ac302d980db9
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: adder
  sessionAffinity: None
  type: ClusterIP
