apiVersion: v1
kind: Service
metadata:
  labels:
    app: front
  name: front
  namespace: b6003234
  resourceVersion: "5050"
  selfLink: /api/v1/namespaces/b6003234/services/front
  uid: 7b869a3c-1b6b-4772-bd05-efaa7693d6a2
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30870
    port: 6060
    protocol: TCP
    targetPort: 8080
  selector:
    app: front
  sessionAffinity: None
  type: LoadBalancer
