apiVersion: v1
kind: Service
metadata:
  labels:
    app: source
  name: source
  namespace: b6003234
  resourceVersion: "5111"
  selfLink: /api/v1/namespaces/b6003234/services/source
  uid: 07b3dfec-0232-4aef-b1a3-bdad246273af
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: source
  sessionAffinity: None
  type: ClusterIP
