apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: suber
  name: suber
  namespace: b6003234
  resourceVersion: "4973"
  selfLink: /apis/extensions/v1beta1/namespaces/b6003234/deployments/suber
  uid: 5bfba720-ff7c-4b11-b6f2-50201268df11
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: suber
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: suber
    spec:
      containers:
      - image: docker.io/chanwit/suber
        imagePullPolicy: Always
        name: suber
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
