apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: source
  name: source
  namespace: b6003234
  resourceVersion: "4870"
  selfLink: /apis/extensions/v1beta1/namespaces/b6003234/deployments/source
  uid: 70e51f09-757b-4962-91a2-a62579845a09
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: source
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: source
    spec:
      containers:
      - image: docker.io/chanwit/source
        imagePullPolicy: Always
        name: source
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
